name: vggt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - autopep8=2.0.4
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.17
  - pip=25.1
  - pycodestyle=2.12.1
  - python=3.10.16
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - accelerate==1.10.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - array-record==0.7.2
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - blessed==1.21.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - ccimport==0.4.4
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - comm==0.2.2
      - configargparse==1.7.1
      - contourpy==1.2.1
      - cuda-bindings==12.9.2
      - cuda-pathfinder==1.2.3
      - cuda-python==12.9.2
      - cudf-cu12==25.8.0
      - cuml-cu12==25.8.0
      - cumm-cu121==0.7.11
      - cupy-cuda12x==13.6.0
      - cuvs-cu12==25.8.0
      - cycler==0.12.1
      - dacite==1.8.1
      - dash==3.2.0
      - dask==2025.7.0
      - dask-cuda==25.8.0
      - dask-cudf-cu12==25.8.0
      - dataclass-array==1.5.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - decord==0.6.0
      - deepspeed==0.16.9
      - diff-gaussian-rasterization==0.0.0
      - distributed==2025.7.0
      - distributed-ucxx-cu12==0.45.1
      - dm-tree==0.1.9
      - docstring-parser==0.16
      - einops==0.8.1
      - einsum==0.3.0
      - embreex==2.17.7.post6
      - etils==1.13.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.115.13
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - ffmpy==0.6.0
      - filelock==3.18.0
      - fire==0.7.1
      - flask==3.1.1
      - flatbuffers==25.2.10
      - fonttools==4.58.2
      - fsspec==2025.5.1
      - gast==0.4.0
      - google-auth==2.16.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.63.1
      - gpustat==1.1.1
      - gradio==5.34.0
      - gradio-client==1.10.3
      - groovy==0.1.2
      - grpcio==1.71.0
      - gsplat==1.5.2+pt23cu121
      - h11==0.16.0
      - h5py==3.13.0
      - hf-xet==1.1.2
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.32.3
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - immutabledict==2.2.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - ipykernel==6.30.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - keras==2.11.0
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - libclang==18.1.1
      - libcudf-cu12==25.8.0
      - libcuml-cu12==25.8.0
      - libcuvs-cu12==25.8.0
      - libkvikio-cu12==25.8.0
      - libraft-cu12==25.8.0
      - librmm-cu12==25.8.0
      - libucx-cu12==1.18.1
      - libucxx-cu12==0.45.1
      - llvmlite==0.44.0
      - locket==1.0.0
      - lpips==0.1.4
      - lxml==5.4.0
      - manifold3d==3.1.1
      - mapbox-earcut==1.0.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.6.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nodeenv==1.9.1
      - numba==0.61.2
      - numba-cuda==0.14.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cccl-cu12==12.9.27
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.5.2
      - nvtx==0.2.13
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - openexr==1.3.9
      - opt-einsum==3.4.0
      - orjson==3.10.18
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.4
      - partd==1.4.2
      - pccm==0.4.16
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==5.13.1
      - plyfile==1.1.2
      - portalocker==3.2.0
      - promise==2.3
      - prompt-toolkit==3.0.51
      - protobuf==3.19.6
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycollada==0.9
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pylibcudf-cu12==25.8.0
      - pylibraft-cu12==25.8.0
      - pynvjitlink-cu12==0.7.0
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - raft-dask-cu12==25.8.0
      - rapids-dask-dependency==25.8.0
      - rapids-logger==0.1.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rich==14.0.0
      - rmm-cu12==25.8.0
      - rpds-py==0.25.1
      - rsa==4.9.1
      - rtree==1.4.0
      - ruff==0.11.13
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.20.0
      - scikit-learn==1.7.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - setuptools==67.6.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - shtab==1.7.2
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - spconv-cu121==2.3.8
      - splines==0.3.2
      - stack-data==0.6.3
      - starlette==0.46.2
      - svg-path==6.3
      - sympy==1.14.0
      - tblib==3.1.0
      - tenacity==9.1.2
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.0
      - tensorflow-estimator==2.11.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.13.0
      - tensorflow-probability==0.19.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - toolz==1.0.0
      - torch==2.3.1
      - torch-scatter==2.1.2+pt23cu121
      - torchvision==0.18.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.4
      - treelite==4.4.1
      - trimesh==4.6.11
      - triton==2.3.1
      - typeguard==2.13.3
      - typer==0.16.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tyro==0.9.24
      - tzdata==2025.2
      - ucx-py-cu12==0.45.0
      - ucxx-cu12==0.45.1
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - vhacdx==0.0.8.post2
      - viser==0.2.23
      - visu3d==1.5.1
      - wadler-lindig==0.1.6
      - waymo-open-dataset-tf-2-11-0==1.6.1
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yourdfpy==0.0.57
      - zict==3.0.0
      - zipp==3.23.0
prefix: /opt/miniconda/envs/vggt
